// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKDqRgM1ZBamm1H7zXsxFPYHgd8aEpcK4',
    appId: '1:651763307724:web:66eab98dc88f508804de69',
    messagingSenderId: '651763307724',
    projectId: 'task-manager-c8107',
    authDomain: 'task-manager-c8107.firebaseapp.com',
    storageBucket: 'task-manager-c8107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVKtzlZQhOWwmJfQ75i12-tJCQr8_U1ss',
    appId: '1:651763307724:android:0d9d88520ee9c47804de69',
    messagingSenderId: '651763307724',
    projectId: 'task-manager-c8107',
    storageBucket: 'task-manager-c8107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_dmuw0LutXj8dYJd6iVe08X7Kx0F8Rg',
    appId: '1:651763307724:ios:144a9eb54a9794fa04de69',
    messagingSenderId: '651763307724',
    projectId: 'task-manager-c8107',
    storageBucket: 'task-manager-c8107.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_dmuw0LutXj8dYJd6iVe08X7Kx0F8Rg',
    appId: '1:651763307724:ios:144a9eb54a9794fa04de69',
    messagingSenderId: '651763307724',
    projectId: 'task-manager-c8107',
    storageBucket: 'task-manager-c8107.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKDqRgM1ZBamm1H7zXsxFPYHgd8aEpcK4',
    appId: '1:651763307724:web:6692f42417d6d22a04de69',
    messagingSenderId: '651763307724',
    projectId: 'task-manager-c8107',
    authDomain: 'task-manager-c8107.firebaseapp.com',
    storageBucket: 'task-manager-c8107.appspot.com',
  );
}
